#!/usr/bin/env python

import click
import datetime
import logging
import settings
import freshtools.cache
import freshtools.summary
import freshtools.models
from freshtools.command import DateTimeParameter, AliasedGroup
from freshtools.log import log_to_stdout
from freshtools.util import (todays_date, n_days_ago_date, this_weeks_date,
                             n_weeks_ago_date, day_starting_and_ending_datetime,
                             week_starting_and_ending_datetime)
from refresh2.auth import DeveloperWebserverFlow, TokenStore, run_flow
from refresh2.api import Api


def get_freshbooks_api(client_id, client_secret, store):
    flow = DeveloperWebserverFlow(client_id, client_secret)
    session = run_flow(flow, store)
    api = Api(session)

    return api


@click.group()
@click.option('-v', '--verbose', count=True)
def cli(verbose):
    if verbose > 0:
        level = logging.DEBUG
    else:
        level = logging.INFO

    log_to_stdout(level)


#
# Cache commands
#

@cli.group()
def cache():
    pass


@cache.command()
def init():
    freshtools.cache.initialize()


@cache.command()
def status():
    freshtools.cache.status()


@cache.command()
@click.argument('models', nargs=-1, required=False)
def show(models):
    if len(models) > 0:
        models = freshtools.models.models_by_name(models)
    else:
        models = freshtools.models.ALL_MODELS

    freshtools.cache.show(models)


@cache.command()
@click.argument('models', nargs=-1, required=False)
def pull(models):
    if len(models) > 0:
        models = freshtools.models.models_by_name(models)
    else:
        models = freshtools.models.ALL_MODELS

    freshtools.cache.pull(api, models)


#
# Summarization commands
#

@cli.group(cls=AliasedGroup)
def summarize():
    pass


@summarize.command()
@click.option('--client', default=None, help='Client name')
@click.option('--start', type=DateTimeParameter(), default=None, help='Start date')
@click.option('--end', type=DateTimeParameter(), default=None, help='End date')
def tasks_by_client(client, start, end):
    client_object = None

    if client is not None:
        client_object = freshtools.models.Client.get_the_one(client)

    summary = freshtools.summary.TasksByClient(
        client=client_object,
        start_date=start,
        end_date=end
    )

    summary.print_report()


@summarize.command(aliases=['days'])
@click.option('--client', default=None, help='Client name')
@click.option('--start', type=DateTimeParameter(), default=None, help='Start date')
@click.option('--end', type=DateTimeParameter(), default=None, help='End date')
def days_by_client_project_task(client, start, end):
    client_object = None

    if client is not None:
        client_object = freshtools.models.Client.get_the_one(client)

    summary = freshtools.summary.DaysByClientProjectTask(
        client=client_object,
        start_date=start,
        end_date=end
    )

    summary.print_report()


@summarize.command(aliases=['weeks'])
@click.option('--client', default=None, help='Client name')
@click.option('--start', type=DateTimeParameter(), default=None, help='Start date')
@click.option('--end', type=DateTimeParameter(), default=None, help='End date')
def weeks_by_client_project(client, start, end):
    client_object = None

    if client is not None:
        client_object = freshtools.models.Client.get_the_one(client)

    summary = freshtools.summary.WeeksByClientProject(
        client=client_object,
        start_date=start,
        end_date=end
    )

    summary.print_report()


@summarize.command()
def today():
    start, end = day_starting_and_ending_datetime(todays_date())
    freshtools.summary.DaysByClientProjectTask(
        start_date=start, end_date=end).print_report()


@summarize.command()
def yesterday():
    start, end = day_starting_and_ending_datetime(n_days_ago_date(1))
    freshtools.summary.DaysByClientProjectTask(
        start_date=start, end_date=end).print_report()


@summarize.command()
def two_days_ago():
    start, end = day_starting_and_ending_datetime(n_days_ago_date(2))
    freshtools.summary.DaysByClientProjectTask(
        start_date=start, end_date=end).print_report()


@summarize.command()
def this_week():
    start, end = week_starting_and_ending_datetime(this_weeks_date())
    freshtools.summary.WeeksByClientProject(
        start_date=start, end_date=end).print_report()


@summarize.command()
def last_week():
    start, end = week_starting_and_ending_datetime(n_weeks_ago_date(1))
    freshtools.summary.WeeksByClientProject(
        start_date=start, end_date=end).print_report()


@summarize.command()
def two_weeks_ago():
    start, end = week_starting_and_ending_datetime(n_weeks_ago_date(2))
    freshtools.summary.WeeksByClientProject(
        start_date=start, end_date=end).print_report()

#
# Main
#

store = TokenStore('.credentials')
api = get_freshbooks_api(
    settings.FRESHBOOKS_CLIENT_ID,
    settings.FRESHBOOKS_CLIENT_SECRET,
    store
)

if __name__ == '__main__':
    cli()
